*** Variable ***
&{TOP_NAV_TEXT}
...			main_title=Django administration			# on the upper left corner
...			dynamic_user_tab=WELCOME, %s. VIEW SITE / CHANGE PASSWORD / LOG OUT
...			welcome=WELCOME								# on the upper right corner
...			view_site=VIEW SITE							# on the upper right corner
...			change_password=CHANGE PASSWORD				# on the upper right corner
...			logout=LOG OUT								# on the upper right corner
